//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMPLEMENTING_REMEMBER_ME_FUNCTIONALITY__CHECK_BOX__40.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int Id { get; set; }

        [DisplayName("User Name")]
        [Required(ErrorMessage = "Username is required :")]
        public string Username { get; set; }

        [DisplayName("User Password")]
        [Required(ErrorMessage = "UserPassword is required :")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DisplayName("Remember ME :")]
        public bool RememberMe { get; set; }
    }
}
