//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPLOADING_AND_RETRIEVING_IMAGES_FROM_DATABASE__43.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Student
    {
        public int id { get; set; }


        [DisplayName("Student Name")]
        [Required(ErrorMessage = "Name is required :")]
        public string FileName { get; set; }

        [DisplayName("Student Class")]
        [Required(ErrorMessage = "Class is required :")]
        public string Standard { get; set; }

        [DisplayName("Choose Image")]
        [Required(ErrorMessage = "Choose Image :")]
        public string Image_Path { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
