//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_APPLICATION_WITH_IMAGES_44.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class EmployeeDB
    {
        public int id { get; set; }
        [DisplayName("Employee Name")]
        [Required(ErrorMessage = "Name is required :")]
        public string Name { get; set; }

        [DisplayName("Employee Designation")]
        [Required(ErrorMessage = "Designation is required :")]
        public string Designation { get; set; }

        [DisplayName("Choose Image")]
        public string Image_Path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
